services:
  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ../backend:/app
    environment:
      - DEBUG=1
      - SECRET_KEY=your-secret-key-here
      - POSTGRES_DB=smartbin_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SQL2025
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://localhost:8000/api
    depends_on:
      - backend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=smartbin_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=SQL2025

volumes:
  postgres_data: